version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/server-2022
    steps:
      - checkout
      - run: pwd
      - run: Write-Host 'Hello, Windows'
      - run: 
          name: Windows Capability Test
          no_output_timeout: 30m
          command: exec.ps1
      - run: 
          working_directory: ~/
          name: Run tests
          command: |
            pwd
workflows:
  my-workflow:
    jobs:
      - build


