version: 2.1

orbs:
  win: circleci/windows@4.1

jobs:
  build:
    executor: win/server-2022
    size: "medium"
    steps:
      - run: Write-Host 'Hello, Windows'
      - run: 
          working_directory: ~/
          name: Run tests
          command: |
            pwd
workflows:
  my-workflow:
    jobs:
      - build


